Validate keys during initialization
jsonapi-rb/jsonapi-renderer pull request #17
Opened 2017-03-24 02:05 UTC by kinopyo

(Follow up https://github.com/jsonapi-rb/jsonapi-renderer/issues/16)

Raises `InvalidKey` exception when initialization:

```ruby
JSONAPI::IncludeDirective.new("friends, comments, posts, author.posts")
# JSONAPI::IncludeDirective::InvalidKey:  comments, posts, author.posts
```

(@beauby Still quite a rough implementation, just to see if this is something we want. If so I'll continue do some refactoring, like extracting the validation part to its own class 🙂)

2017-04-20 07:29 UTC, kinopyo commented
@beauby may I get some feedback 🙏 🙇  (before I forget what I was doing 😅 )

2017-04-24 01:51 UTC, beauby commented
Hi @kinopyo – will do it tomorrow hopefully (do not hesitate to ping me if I don't !)

2017-04-25 14:14 UTC, kinopyo commented
@beauby (human low tech ping 👋 😅 )

2017-04-27 14:35 UTC, beauby commented
Hi @kinopyo – thanks for bearing with my slow reviews! ;)

While the current approach has the benefit of listing all invalid keys, I'd rather have the initializer `raise InvalidKey` as soon as it hits the first invalid key. There are mainly two reasons why I prefer this fail fast strategy:
1. once one key is invalid, the parser no longer works under the same assumptions, which means the following invalid keys may or may not make sense to the user (this is more of a general point about failing upon first invalid token in parsing, as I believe in the current implementation this would not be a problem);
2. It's much less code (it becomes mainly a matter of validating the key [here](https://github.com/jsonapi-rb/jsonapi-renderer/blob/master/lib/jsonapi/include_directive.rb#L19), and `raise InvalidKey` if invalid), and a smaller overhead.

What do you think?

2017-05-24 07:56 UTC, kinopyo commented on lib/jsonapi/include_directive.rb
> +      /^(?![\s\-_])[\w\s\-\*]+(?<![\s\-_])$/
Any advice to "outsource" this regex? I'm a horrible regex reader/writer, if there is a cheap but reliable way of checking if a key is valid or not, I'll dump this line go for it 😅

2017-05-24 07:59 UTC, kinopyo commented
@beauby oops sorry for keeping you waiting 🙇 , and many thanks for your inputs! I think the fail-fast strategy is ok, and the gain of less code is more rewarding 🙂 I've updated the PR and resolved Hound comments, what do you think?

2017-05-24 08:57 UTC, beauby requested changes
Small style suggestion + let's fix the regex and we can merge :+1:.

2017-05-24 08:57 UTC, beauby commented on lib/jsonapi/include_directive.rb
> +        validate(key)
`raise InvalidKey, key unless valid?(key)`

2017-05-24 08:57 UTC, beauby commented on lib/jsonapi/include_directive.rb
> +      /^(?![\s\-_])[\w\s\-\*]+(?<![\s\-_])$/
This regex does not seem correct (numbers for instance are allowed in member names).

2017-05-24 11:52 UTC, kinopyo commented on lib/jsonapi/include_directive.rb
> +      /^(?![\s\-_])[\w\s\-\*]+(?<![\s\-_])$/
Ohhh! This `\w` should also represent numbers, my explanation in the comment was bad.. updated in 57b8878

> \w	Any word character (letter, number, underscore)

2017-05-24 11:57 UTC, kinopyo commented on lib/jsonapi/include_directive.rb
> +        validate(key)
pulled up in 046cb68 (style wise feeling slightly uncomfortable when the method takes two arguments 😅, but I guess in this case it's relatively simple to follow )

2017-05-24 11:59 UTC, kinopyo commented
@beauby Thank you for you quick review! Pushed 2 fixes 🎈 (and let me know if you prefer to have a single rebased commit before merging 🙇 )

2017-06-03 18:09 UTC, beauby approved these changes

2017-06-03 18:10 UTC, beauby commented
Looks good, will merge tonight! Thanks for following up with this! :+1:

2017-06-03 21:01 UTC, beauby commented on lib/jsonapi/include_directive.rb
> +      # contains a-zA-Z, 0-9, and hyphen/underscore/space in member names
Could you replace these comments with a link to http://jsonapi.org/format/#document-member-names? Also, the regex still seems to exclude some allowed characters such as 
> U+0080 and above (non-ASCII Unicode characters; not recommended, not URL safe)

2019-03-10 18:57 UTC, dawidof commented
https://github.com/jsonapi-rb/jsonapi-renderer/pull/36

2019-03-10 18:58 UTC, closed without merging